services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dermatologico
    ports:
      # Mapeamos al host 3307 para evitar conflictos si MySQL ya corre en Windows
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: .
    environment:
      PORT: 3000
      # Use the host's MySQL (Windows) via host.docker.internal
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: dermatologico
      JWT_SECRET: secreto
      # Permitir orígenes para CORS (comas separadas). Añadir la URL de Pages y la del túnel ngrok.
      CORS_ORIGINS: "http://localhost:4200,https://rortizi396.github.io,https://nonbotanically-studentless-kasey.ngrok-free.dev"
      # When connecting to an existing DB on the host, skip automatic schema init/seed
      SKIP_DB_INIT: "true"
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db-data:
    driver: local
