name: CI - Run endpoint smoke tests

on:
  push:
    branches:
      - 'ci/test-endpoints'

jobs:
  run-tests:
    name: Run endpoint smoke tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Debug: show repo contents
        run: |
          echo "PWD=$(pwd)";
          echo "Listing top-level files:";
          ls -la . | sed -n '1,200p';
          echo "Listing scripts/ (if present):";
          ls -la scripts || true;

      - name: Ensure test script present (fallback to main)
        run: |
          if [ ! -f ./scripts/test_endpoints.js ]; then
            echo "scripts/test_endpoints.js not found in checkout; attempting to fetch from origin/main";
            git fetch origin main --depth=1 || true;
            git checkout origin/main -- scripts/test_endpoints.js || true;
          else
            echo "scripts/test_endpoints.js present";
          fi

      - name: Fallback: download test script from raw GitHub
        run: |
          if [ ! -f ./scripts/test_endpoints.js ]; then
            echo "Attempting to download scripts/test_endpoints.js from raw.githubusercontent.com";
            mkdir -p scripts;
            curl -fsS -o ./scripts/test_endpoints.js https://raw.githubusercontent.com/Rortizi396/dermatologia-app/main/scripts/test_endpoints.js || true;
            if [ -f ./scripts/test_endpoints.js ]; then
              echo "Downloaded script successfully";
              ls -la ./scripts/test_endpoints.js;
            else
              echo "Could not download script; will fail later";
            fi
          else
            echo "Script already present; skipping download";
          fi

      - name: Run endpoint tests and capture output
        run: |
          set -o pipefail
          echo "Running node dermatologia-app/scripts/test_endpoints.js from $(pwd) ...";
          node dermatologia-app/scripts/test_endpoints.js https://dermatologia-backend-th09.onrender.com 2>&1 | tee test-output.log

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: endpoint-test-output
          path: test-output.log
