name: DISABLED - Build and deploy to GitHub Pages (gh-pages branch)

# Disabled because we deploy via Pages from main/docs now.
on:
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    if: ${{ false }} # disabled — using Pages: branch main/docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build production (for GitHub Pages)
        run: npm run build:prod:pages

      - name: Inject backend API URL into built index.html
        # Requires a repo secret named BACKEND_API_URL with value like https://dermatologia-backend-th09.onrender.com
        run: node ./scripts/write-env.js --dist=dist/dermatologia-app --apiUrl=${{ secrets.BACKEND_API_URL }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/dermatologia-app
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
